### PR TITLE
turn constants into constants

### PR DESCRIPTION
**Pull request by arnetheduck**
* allows compiling without header file (`nlvm`)
* allows nim to inline constants
* constants in header are part of abi and won't change, this is safe

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
> constants in header are part of abi and won't change

MINIUPNPC_VERSION and MINIUPNPC_API_VERSION are guaranteed to change.

The whole point of a thin wrapper is to avoid copy-pasting code, as much as possible. We already introduce fragility by copying function signatures. The least we can do is not copy constant values.

If you need a special case for nlvm, how about adding a new parameter to `importConst()` for the defined value and have it generate the `const` you want, only if it's running under your compiler? This way we minimise the damage.

**Comment by arnetheduck** [comment]
> MINIUPNPC_VERSION and MINIUPNPC_API_VERSION are guaranteed to change.

only together with the pinned submodule - which is why the submodule way was chosen to begin with

> how about adding a new parameter to importConst()

that seems like asking for the worst of both worlds - having the constant values there but not using them _and_ generating worse code (ie two variables, and neither `var` nor `let` expresses a constant to the compiler, which was the intent of upstream)

it is fairly standard practise to use constant values for `#define` in wrappers, not sure I see the problem really - this is generally why people use stuff like `c2nim` to generate them, so there won't be any manual copy-paste step, but even when they don't, the maintenance is minimal and there are non-nlvm benefits as well.

**Comment by stefantalpalaru** [comment]
> only together with the pinned submodule

This is a generic library that suports system-wide installations of miniupnp and libnatpmp: https://github.com/status-im/nim-nat-traversal#usage

> which was the intent of upstream

Upstream's intent was for me to make a wrapper that only works properly for a specific revision of their library?

> that seems like asking for the worst of both worlds 

No, it's just minimising the damage you want to introduce.

> it is fairly standard practise to use constant values for #define in wrappers

I sure hope not. The Python wrapper is done in C, using the standard header: https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/miniupnpcmodule.c

Only the Java wrapper parses headers to spit out its "public static final" constants in a Java interface, but that wrapper is shipped with the library and it's generated on the fly by the build system (`make jar`).

> not sure I see the problem really

Not being able to wrap a system library and print its version. It's the "hello world" of wrappers.

> this is generally why people use stuff like c2nim to generate them, so there won't be any manual copy-paste step

You can't rely on c2nim output working out of the box, like you can with JNAerator.

> there are non-nlvm benefits as well

There is none. Instead of being able to wrap almost any library version, you'll only be able to wrap one of them and output its version correctly, because you copied all C header defines from that specific version.

> the maintenance is minimal

Great. Accept the compromise and maintain your version of those constants only for nlvm.

**Comment by arnetheduck** [comment]
> Upstream's intent was for me to make a wrapper

that's what happens with most wrappers since you need to describe to Nim what the library is doing - how big the structs are, what the constant values are, which are available for a given version etc etc etc.. your wrapper is inevitably tied to some specific version, and might, _if_ upstream is careful, work with others.

> I sure hope not.

https://github.com/nim-lang/Nim/blob/devel/lib/posix/posix_linux_amd64_consts.nim

> The Python wrapper is done in C

that's because python wrappers are written in C, not in Python?

> You can't rely on c2nim output working out of the box, like you can with JNAerator.

they solve the same problem, one has more bugs

> Not being able to wrap a system library and print its version. 

well, that's pretty fragile anyway since header and wrapper version might mismatch.. you wouldn't use a header file from 1.4 with 1.3 library for example. ie a wrapper is really the header file written in another language, as closely as possible.. but regardless, we can leave the version as a fake var, will that be better?

> There is none. 

better codegen? usable constants in situations that demand constants?

**Comment by stefantalpalaru** [comment]
> your wrapper is inevitably tied to some specific version, and might, if upstream is careful, work with others.

It already works with the vast majority of versions out there. What you want is to break that for everybody, not just for yourself.

> https://github.com/nim-lang/Nim/blob/devel/lib/posix/posix_linux_amd64_consts.nim

Terrible strategy. "tools/detect/detect.nim" should be executed at every compiler build, not manually when something breaks.

>  python wrappers are written in C, not in Python

So even the expert beginners developing Python figured this one out.

> they solve the same problem, one has more bugs

They solve the same problem, one doesn't work.

> header and wrapper version might mismatch

Might? The library version is not copied and pasted into the wrapper right now, so there is no mismatch.

> we can leave the version as a fake var, will that be better?

It would be better to support that construct in nlvm. If that's not possible, it would be less harmful to only screw nlvm users with conditional code just for them.

> better codegen?

Worse is not better. Worse is worse.

> usable constants in situations that demand constants?

So you want to copy the version number so the API user cannot intentionally change the version number?

**Comment by arnetheduck** [comment]
> So even the expert beginners developing Python figured this one out.

well, so does lua and other dynamic languages - it's in the nature of the way the language is implemented. on the other hand, compiled languages (rust, Java, etc) tend to describe the ABI in their own language using the platform C ABI... for example, python programs tend not to link statically as is common with c.

> Worse is not better. 

you still haven't explained how generating two _variables_ for a _constant_ is better..

but whatever - we can close this PR, it's a convenience mostly.

**Comment by arnetheduck** [comment]
rust: https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs#L1820

**Comment by stefantalpalaru** [comment]
> so does lua and other dynamic languages - it's in the nature of the way the language is implemented

Not really. You can make a C wrapper for Nim that hides all the miniupnpc API and headers, just like dynamic languages do it.

> you still haven't explained how generating two variables for a constant is better..

I did, multiple times. It boils down to this: https://github.com/status-im/nim-nat-traversal/blob/e3fd23e90f661f51f028f78202eb4de1e6128ea9/examples/miniupnpc_test.nim#L22

> but whatever - we can close this PR, it's a convenience mostly.

Make your convenience not inconvenience me. I already gave you a solution for that. Do I also have to implement it?

**Comment by arnetheduck** [comment]
the fundamental problem with that approach is that we get a when jungle branch that's almost never tested - you'll agree that the constants (like `UPNPCOMMAND_SUCCESS`) won't change, so these pose no maintenance and do provide better codegen.

so, the compromise here would be to use the variable constants (haha) for version and constant constants for the rest - or we just skip this, and I'll maintain a fork somewhere until we decide we actually need `nlvm` (for now, I'm just testing it, to see what happens with wasm..).

**Comment by stefantalpalaru** [comment]
Won't nlvm choke on 2 instances of `importConst()` just like it does on 30 instances of it?

**Comment by arnetheduck** [comment]
it only chokes on what is used (dead-code-elim).. fortunately we don't use these.

**Comment by arnetheduck** [comment]
or we can simply not expose version - it's kind of dumb anyway to have it in the header file: consider that a program is compiled with `1.0`, then system is upgraded to `1.1` - program will continue thinking / printing it's using 1.0 even though the dynamically linked version is `1.1`...

**Comment by stefantalpalaru** [comment]
Now you're breaking the examples. I think distro packagers are supposed to rebuild their packages against new library versions, so the versions are always in sync.

**Comment by arnetheduck** [comment]
> I think distro packagers are supposed to rebuild their packages against new library versions, so the versions are always in sync.

I'm referring to when the user has some distro version installed of miniupnpc but uses nim-nat-traversal from say.. nimble.. for their own programs. I don't condone this behaviour since it leads to situations like this, but it's a reality.

**Comment by arnetheduck** [comment]
> Now you're breaking the examples. 

there we go

**Pull request merged**
